name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-PHP-8_1:
    name: Build, test and publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '7.4', '8.0', '8.1' ]
        include:
          - version: 'latest'
            
    steps:
      - uses: actions/checkout@v2
        name: Check out code
          
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
        
      - name: log in to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build image and push to registry
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          cache-from: type=gha, scope=${{ github.workflow }}-php-${{ matrix.version }}
          cache-to: type=gha, scope=${{ github.workflow }}-php-${{ matrix.version }}, mode=max
          context: .
          file: ./images/php/Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.version }}
            BUILD_DATE=$(TZ=":UTC" date +"%Y-%m-%d %H:%M:%S (%Z %z)")
            BUILD_INFO=${GITHUB_SHA::7}
          tags: beeyev/php-ci-pipline:${{ matrix.version }}
          pull: true
          push: true
          
#       - name: build and push the acng latest image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile.bullseye
#           platforms: linux/amd64
#           pull: true
#           push: true
#           tags: mfontani/acng:latest
#           build-args: BUILDKIT_INLINE_CACHE=1
#           cache-from: mfontani/acng:latest
          
#       - uses: mr-smithers-excellent/docker-build-push@v5
#         name: Build & push Docker image
#         with:
#           image: ${{ secrets.DOCKERHUB_USERNAME }}/php-ci-pipline
#           tags: 8.1
#           registry: docker.io
#           dockerfile: images/php/Dockerfile
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
          
#   build-PHP-8_1:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         name: Check out code
#       - uses: mr-smithers-excellent/docker-build-push@v5
#         name: Build & push Docker image
#         with:
#           image: ${{ secrets.DOCKERHUB_USERNAME }}/php-ci-pipline
#           tags: 8.1
#           registry: docker.io
#           dockerfile: images/php/Dockerfile
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
  
